import { EnrichedCandidate } from './types';
import { ALL_INTERVIEWERS } from '../../data/interviewers';

export const DEMO_ENRICHED_CANDIDATES: EnrichedCandidate[] = [
  {
    id: 'cand-1',
    name: 'Aanya Patel',
    gender: 'Female',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    role: 'Principal AI & Systems Architect',
    yearsOfExperience: 11,
    experienceTier: 'expert',
    previousCompany: 'Razorpay',
    workMode: 'Remote',
    date: 'Today, 4:30 PM',
    overallScore: 96,
    recommendation: 'Strong Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 97,
    problemSolvingScore: 96,
    leadershipScore: 94,
    businessScore: 95,
    communicationScore: 98,
    standoutPraise:
      'Top Performer in Cohort. Unparalleled precision in multi-agent orchestration and low-latency p99 budgeting.',
    keyStrengths: [
      'Semantic Vector Pruning',
      'Multi-Agent State Sync',
      'p99 Latency SLA (<30ms)',
      'Kafka Partition Fencing',
      'Model Guardrails',
    ],
    quoteEvidence:
      '"Context window compression is done via semantic vector pruning before sending prompts to Llama; latency is sub-30ms with zero loss in cross-turn continuity."',
    status: 'Evaluated',
    jargonAudit: {
      practicalDepthRatio: 94,
      buzzwordDensity: 'Low (6%)',
      verifiedConcreteMetricsCount: 9,
      auditSummary:
        'Candidate demonstrated deep hands-on mastery over GPU VRAM scheduling, token memory limits, and distributed cache topologies.',
      scrutinizedTerms: ['Semantic Pruning', 'Vector Clocks', 'Distributed Consensus', 'p99 SLA'],
    },
    competencies: [
      { name: 'Distributed Architecture & System Design', score: 98, weight: '30%', verdict: 'Exceeds Bar', color: 'indigo' },
      { name: 'Product Trade-offs & Customer Empathy', score: 94, weight: '20%', verdict: 'Exceeds Bar', color: 'purple' },
      { name: 'Engineering Leadership & Velocity', score: 95, weight: '20%', verdict: 'Exceeds Bar', color: 'blue' },
      { name: 'Enterprise SLA Reliability & Security', score: 96, weight: '15%', verdict: 'Exceeds Bar', color: 'emerald' },
      { name: 'Behavioral Dynamics & STAR Methodology', score: 97, weight: '15%', verdict: 'Exceeds Bar', color: 'amber' },
    ],
    sampleQA: [
      {
        interviewerIndex: 0,
        interviewerName: 'Rohan Sharma',
        interviewerTitle: 'Lead Systems Architect',
        roleBadge: 'Distributed Systems & Concurrency',
        score: 98,
        verdict: 'Strong Endorsement',
        question:
          'How do you handle context window saturation in multi-agent conversations without degrading latency ceilings?',
        answer:
          'We run an asymmetric hierarchical memory model. Immediate dialogue runs in a sliding ephemeral window, while historical turns are asynchronously summarized and indexed into an HNSW vector store. When an agent needs past context, we perform semantic similarity retrieval and prune tokens using BM25 hybrid ranking, keeping total prompt injection under 1.8k tokens with p99 under 28ms.',
        feedback:
          'Exceptional architectural rigor; zero reliance on superficial buzzwords; concrete latency benchmarks.',
      },
      {
        interviewerIndex: 1,
        interviewerName: 'Priya Mehta',
        interviewerTitle: 'Principal Product Manager',
        roleBadge: 'Product Empathy & Business ROI',
        score: 94,
        verdict: 'Strong Endorsement',
        question: 'What business impact did this memory optimization achieve for end-users and infrastructure cost?',
        answer:
          'By trimming token payloads by 64%, our per-turn LLM inference spend dropped from $0.012 to $0.0039, saving $42k/month. More importantly, time-to-first-token dropped from 1.4s to 380ms, boosting user interview completion rates by 19%.',
        feedback: 'Grounded technical architecture in measurable conversion metrics and bottom-line dollar savings.',
      },
    ],
    barRaiserCheck: {
      topic: 'Zero-Latency Hallucination Guardrails',
      candidateClaim: 'We run real-time semantic hallucination checks inline before audio synthesis.',
      aiProbe:
        'Rohan & Neha probed whether a second LLM verification step creates unacceptable 800ms delays in a conversational voice pipeline.',
      candidateAdjustment:
        'Candidate clarified that verification runs speculative parallel decode with early cancellation if token entropy spikes above 0.72.',
      verdict: 'Exceptional technical depth and rapid, transparent calibration under cross-examination.',
    },
    onboardingPlan: [
      'Days 1–30: Audit real-time voice latency budget across Agora edge nodes & mentor junior engineers on memory management.',
      'Days 31–60: Partner with Product & VP of Engineering to productionize enterprise multi-agent deliberation pipelines.',
      'Days 61–90: Represent team in hiring committees as Bar-Raiser for Senior & Staff engineering loops.',
    ],
  },
  {
    id: 'cand-2',
    name: 'Jordan Reed',
    gender: 'Male',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    role: 'Staff Distributed Systems Architect',
    yearsOfExperience: 10,
    experienceTier: 'senior',
    previousCompany: 'Swiggy',
    workMode: 'Onsite',
    date: 'Today, 2:15 PM',
    overallScore: 94,
    recommendation: 'Strong Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 96,
    problemSolvingScore: 95,
    leadershipScore: 92,
    businessScore: 91,
    communicationScore: 96,
    standoutPraise:
      'Top Male Performer in Cohort. Remarkable expertise in transactional outbox patterns, Raft leases, and zero-downtime database migrations.',
    keyStrengths: [
      'Distributed Cache Invalidation',
      'p99 Latency SLAs (<45ms)',
      'Kafka Partition Fencing',
      'Enterprise Zero-Downtime',
      'STAR Conflict Resolution',
    ],
    quoteEvidence:
      '"We avoided distributed locks across regions by implementing deterministic hash routing on the partition key at the API gateway layer, falling back to an event-sourced outbox pattern with idempotent dedup tokens."',
    status: 'Evaluated',
    jargonAudit: {
      practicalDepthRatio: 91,
      buzzwordDensity: 'Low (9%)',
      verifiedConcreteMetricsCount: 8,
      auditSummary:
        'Candidate grounded architectural choices in real production constraints (OS socket buffers, disk sync latency, and Kafka partition rebalancing).',
      scrutinizedTerms: ['Distributed Consensus', 'Raft Leases', 'Kafka Outbox', 'Vector Clocks'],
    },
    competencies: [
      { name: 'Distributed Architecture & System Design', score: 96, weight: '30%', verdict: 'Exceeds Bar', color: 'indigo' },
      { name: 'Product Trade-offs & Customer Empathy', score: 91, weight: '20%', verdict: 'Exceeds Bar', color: 'purple' },
      { name: 'Engineering Leadership & Velocity', score: 92, weight: '20%', verdict: 'Exceeds Bar', color: 'blue' },
      { name: 'Enterprise SLA Reliability & Security', score: 95, weight: '15%', verdict: 'Exceeds Bar', color: 'emerald' },
      { name: 'Behavioral Dynamics & STAR Methodology', score: 96, weight: '15%', verdict: 'Exceeds Bar', color: 'amber' },
    ],
    sampleQA: [
      {
        interviewerIndex: 0,
        interviewerName: 'Rohan Sharma',
        interviewerTitle: 'Lead Systems Architect',
        roleBadge: 'Distributed Systems & Concurrency',
        score: 96,
        verdict: 'Strong Endorsement',
        question:
          'In an active-active setup across geographic regions, how do you handle cross-region link partitions during peak burst?',
        answer:
          'A distributed 2PC across cross-continental regions incurs at least 70 to 120ms just in speed-of-light round trips. We instituted an account-affinity partitioning strategy where each ledger partition has a single designated primary home region determined by consistent hashing at edge Envoy proxies. Commits occur locally to Raft quorum in under 8ms, and cross-region replication is asynchronous via transactional outbox Kafka topics.',
        feedback:
          'Immediate rejection of anti-patterns (2PC over WAN), clean use of vector clocks, and concrete understanding of latency ceilings.',
      },
    ],
    barRaiserCheck: {
      topic: 'Linearizable Consistency across Global WAN',
      candidateClaim: 'We achieved strict linearizable consistency across three global AWS regions in under 30 milliseconds.',
      aiProbe:
        'Rohan & Neha challenged that speed of light in fiber makes cross-continental round-trips >70ms physically.',
      candidateAdjustment:
        'Candidate immediately clarified that strict linearizability was localized to the primary region; WAN guarantees were causal consistency.',
      verdict: 'Demonstrated high intellectual integrity and transparent self-correction under committee pressure.',
    },
    onboardingPlan: [
      'Days 1–30: Lead architectural review of core transaction ingestion mesh & shadow P1 on-call rotations.',
      'Days 31–60: Partner with PM & Enterprise to define tier-1 enterprise latency SLOs & migration runbooks.',
      'Days 61–90: Host team-wide training on Raft consensus protocols & chaos engineering failure injection drills.',
    ],
  },
  {
    id: 'cand-3',
    name: 'Rhea Shenoy',
    gender: 'Female',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    role: 'Staff Backend & Concurrency Lead',
    yearsOfExperience: 8,
    experienceTier: 'senior',
    previousCompany: 'Flipkart',
    workMode: 'Hybrid',
    date: 'Yesterday, 11:15 AM',
    overallScore: 91,
    recommendation: 'Strong Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 93,
    problemSolvingScore: 92,
    leadershipScore: 89,
    businessScore: 88,
    communicationScore: 93,
    standoutPraise:
      'Top Problem Solver. Excellent grasp of partition isolation, lock-free data structures, and backpressure shed algorithms.',
    keyStrengths: [
      'High-throughput Ledger',
      'Lock-Free Data Structures',
      'Backpressure Shedding',
      'Kafka Partition Fencing',
    ],
    quoteEvidence:
      '"We handled 45,000 writes/sec by isolating hotspot accounts into dynamic bucket queues with backpressure shedding, preventing cascade memory exhaustion."',
    status: 'Evaluated',
  },
  {
    id: 'cand-4',
    name: 'Aryan Shah',
    gender: 'Male',
    city: 'Gurugram',
    state: 'Delhi-NCR',
    country: 'India',
    role: 'Senior Cloud & Platform Engineer',
    yearsOfExperience: 6,
    experienceTier: 'mid',
    previousCompany: 'Zomato',
    workMode: 'Remote',
    date: 'Yesterday, 2:45 PM',
    overallScore: 88,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS.slice(0, 4),
    technicalScore: 89,
    problemSolvingScore: 88,
    leadershipScore: 86,
    businessScore: 87,
    communicationScore: 90,
    standoutPraise:
      'Solid platform engineer with strong Kubernetes operator knowledge and automated canary rollback automation.',
    keyStrengths: ['Kubernetes Operators', 'Envoy WASM Filters', 'Chaos Drills', 'CI/CD Canary Rollbacks'],
    quoteEvidence:
      '"Built custom Envoy WASM filters to authenticate and rate-limit API calls at the edge, reducing internal service mesh transit by 34%."',
    status: 'Evaluated',
  },
  {
    id: 'cand-5',
    name: 'Pooja Deshmukh',
    gender: 'Female',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    role: 'Lead Product Systems Engineer',
    yearsOfExperience: 7,
    experienceTier: 'mid',
    previousCompany: 'PhonePe',
    workMode: 'Onsite',
    date: 'Aug 29, 2026',
    overallScore: 89,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 88,
    problemSolvingScore: 90,
    leadershipScore: 89,
    businessScore: 93,
    communicationScore: 85,
    standoutPraise:
      'Exceptional business empathy. Articulated clear trade-offs between eventual consistency and checkout conversion funnels.',
    keyStrengths: [
      'Conversion SLA Alignment',
      'Event-Driven Microservices',
      'Cross-Functional Strategy',
      'GraphQL Federation',
    ],
    quoteEvidence:
      '"We traded off immediate consistency on user profile analytics to protect 99.999% availability on user-facing payment checkout paths."',
    status: 'Evaluated',
  },
  {
    id: 'cand-6',
    name: 'Kabir Mehra',
    gender: 'Male',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    role: 'Staff SRE & Resilience Engineer',
    yearsOfExperience: 9,
    experienceTier: 'senior',
    previousCompany: 'Amazon AWS',
    workMode: 'Remote',
    date: 'Aug 28, 2026',
    overallScore: 86,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS.slice(0, 4),
    technicalScore: 88,
    problemSolvingScore: 85,
    leadershipScore: 84,
    businessScore: 82,
    communicationScore: 91,
    standoutPraise:
      'Deep knowledge of eBPF network tracing, automated failover triggers, and p99.99 outlier debugging.',
    keyStrengths: [
      'eBPF Tracing',
      'Automated Circuit Breakers',
      'Chaos Engineering',
      'SLO Alert Telemetry',
    ],
    quoteEvidence:
      '"De-risked distributed database failovers by running continuous chaos monkey drills in staging with zero human intervention required."',
    status: 'Evaluated',
  },
  {
    id: 'cand-7',
    name: 'Ishita Sen',
    gender: 'Female',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    role: 'Senior ML Systems Engineer',
    yearsOfExperience: 5,
    experienceTier: 'mid',
    previousCompany: 'Uber India',
    workMode: 'Hybrid',
    date: 'Aug 27, 2026',
    overallScore: 85,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 87,
    problemSolvingScore: 86,
    leadershipScore: 82,
    businessScore: 80,
    communicationScore: 90,
    standoutPraise:
      'Strong fundamentals in INT4/INT8 speculative decoding, GPU cluster utilization, and streaming token pipelines.',
    keyStrengths: ['Quantization (INT4/8)', 'GPU VRAM Optimization', 'Speculative Decoding', 'Streaming Inference'],
    quoteEvidence:
      '"Achieved 3.4x higher token throughput by batching speculative decodes across dual H100 clusters with vLLM tensor parallelism."',
    status: 'Evaluated',
  },
  {
    id: 'cand-8',
    name: 'Devansh Verma',
    gender: 'Male',
    city: 'Noida',
    state: 'Delhi-NCR',
    country: 'India',
    role: 'Full-Stack Tech Lead',
    yearsOfExperience: 4,
    experienceTier: 'mid',
    previousCompany: 'CRED',
    workMode: 'Remote',
    date: 'Aug 26, 2026',
    overallScore: 78,
    recommendation: 'Leaning Hire',
    panelUsed: [ALL_INTERVIEWERS[1], ALL_INTERVIEWERS[2], ALL_INTERVIEWERS[3]],
    technicalScore: 79,
    problemSolvingScore: 77,
    leadershipScore: 78,
    businessScore: 80,
    communicationScore: 76,
    standoutPraise:
      'Good developer velocity; needs more grounding in distributed failovers and cross-region replication mechanics.',
    keyStrengths: ['React 19 Concurrent Mode', 'GraphQL Schema Stitching', 'Component Virtualization'],
    quoteEvidence:
      '"Migrated micro-frontends to isolated web workers to prevent main-thread jank during heavy table virtualization."',
    status: 'Under Review',
  },
  {
    id: 'cand-9',
    name: 'Meera Nambiar',
    gender: 'Female',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    role: 'Enterprise Security & Compliance Lead',
    yearsOfExperience: 8,
    experienceTier: 'senior',
    previousCompany: 'Stripe',
    workMode: 'Remote',
    date: 'Aug 25, 2026',
    overallScore: 87,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 89,
    problemSolvingScore: 86,
    leadershipScore: 88,
    businessScore: 85,
    communicationScore: 87,
    standoutPraise: 'Top Enterprise Security Score. Zero-trust advocate with practical KMS tenant isolation architecture.',
    keyStrengths: [
      'SOC2/HIPAA Zero Trust',
      'KMS Tenant Isolation',
      'Asymmetric Token Rotation',
      'Cryptographic Envelope Encryption',
    ],
    quoteEvidence:
      '"Enforced cryptographic envelope encryption per tenant DB row with hardware security module root-of-trust, passing audit with zero findings."',
    status: 'Evaluated',
  },
  {
    id: 'cand-10',
    name: 'Kunal Singhania',
    gender: 'Male',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    role: 'DevOps & Infrastructure Engineer',
    yearsOfExperience: 2,
    experienceTier: 'beginner',
    previousCompany: 'Infosys',
    workMode: 'Onsite',
    date: 'Aug 24, 2026',
    overallScore: 62,
    recommendation: 'Leaning No Hire',
    panelUsed: [ALL_INTERVIEWERS[0], ALL_INTERVIEWERS[2], ALL_INTERVIEWERS[3]],
    technicalScore: 64,
    problemSolvingScore: 60,
    leadershipScore: 62,
    businessScore: 65,
    communicationScore: 59,
    standoutPraise:
      'Familiar with standard CI/CD, but missed multiple probing questions on RTO/RPO disaster recovery failovers.',
    keyStrengths: ['Terraform IaC', 'Docker Compose'],
    quoteEvidence:
      '"We used standard Kubernetes rolling deployments without automated canary rollback metrics or circuit breakers under spike load."',
    status: 'Flagged',
  },
  {
    id: 'cand-11',
    name: 'Sneha Kulkarni',
    gender: 'Female',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    role: 'Graduate AI/ML Trainee (Fresher 2026)',
    yearsOfExperience: 0,
    experienceTier: 'fresher',
    previousCompany: 'None (Fresher / Campus Graduate)',
    workMode: 'Onsite',
    date: 'Aug 23, 2026',
    overallScore: 85,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS.slice(0, 3),
    technicalScore: 86,
    problemSolvingScore: 84,
    leadershipScore: 80,
    businessScore: 82,
    communicationScore: 88,
    standoutPraise:
      'High-potential campus graduate with strong algorithmic fundamentals and published thesis in transformer attention.',
    keyStrengths: ['Python NumPy & PyTorch', 'Data Structures & Algorithms', 'Fast Learner'],
    quoteEvidence:
      '"Trained an attention-based multi-lingual sentiment classifier achieving 92% F1 on benchmark datasets during university research thesis."',
    status: 'Evaluated',
  },
  {
    id: 'cand-12',
    name: 'Aditya Joshi',
    gender: 'Male',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    role: 'Associate Software Engineer (0–1 Yr)',
    yearsOfExperience: 1,
    experienceTier: 'fresher',
    previousCompany: 'None (Fresher / Trainee)',
    workMode: 'Onsite',
    date: 'Aug 22, 2026',
    overallScore: 83,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS.slice(0, 3),
    technicalScore: 84,
    problemSolvingScore: 82,
    leadershipScore: 80,
    businessScore: 81,
    communicationScore: 85,
    standoutPraise:
      'Demonstrated sharp code cleanliness and quick turnaround on async concurrency questions.',
    keyStrengths: ['TypeScript & Node.js', 'REST API Design', 'SQL Optimization'],
    quoteEvidence:
      '"Built end-to-end webhook ingestion handling 1,500 payload dispatches per minute with exponential backoff retries."',
    status: 'Evaluated',
  },
  {
    id: 'cand-13',
    name: 'Tanvi Roy',
    gender: 'Female',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    role: 'Junior Frontend Developer (1–3 Yrs)',
    yearsOfExperience: 2,
    experienceTier: 'beginner',
    previousCompany: 'Wipro',
    workMode: 'Remote',
    date: 'Aug 21, 2026',
    overallScore: 82,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS.slice(0, 3),
    technicalScore: 83,
    problemSolvingScore: 81,
    leadershipScore: 80,
    businessScore: 81,
    communicationScore: 86,
    standoutPraise:
      'Strong component hygiene and accessibility standards for cross-device responsive web design.',
    keyStrengths: ['React 19 & Next.js', 'Tailwind CSS', 'State Management'],
    quoteEvidence:
      '"Implemented responsive component design system reducing UI bundle size by 28% and boosting Lighthouse performance score to 98."',
    status: 'Evaluated',
  },
  {
    id: 'cand-14',
    name: 'Rohan Varma',
    gender: 'Male',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    role: 'Software Engineer - Backend (1–3 Yrs)',
    yearsOfExperience: 3,
    experienceTier: 'beginner',
    previousCompany: 'TCS Digital',
    workMode: 'Hybrid',
    date: 'Aug 20, 2026',
    overallScore: 81,
    recommendation: 'Hire',
    panelUsed: ALL_INTERVIEWERS.slice(0, 3),
    technicalScore: 82,
    problemSolvingScore: 80,
    leadershipScore: 81,
    businessScore: 79,
    communicationScore: 84,
    standoutPraise:
      'Solid transactional DB acumen and clean API schema design.',
    keyStrengths: ['PostgreSQL Indexing', 'Docker & CI/CD', 'API Security'],
    quoteEvidence:
      '"Refactored nested SQL join queries into partitioned materialized views, cutting query execution time from 1.2s to 45ms."',
    status: 'Evaluated',
  },
  {
    id: 'cand-15',
    name: 'Vikramaditya Rao',
    gender: 'Male',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    role: 'Distinguished Infrastructure Architect (10+ Yrs)',
    yearsOfExperience: 14,
    experienceTier: 'expert',
    previousCompany: 'Microsoft IDC',
    workMode: 'Remote',
    date: 'Aug 19, 2026',
    overallScore: 95,
    recommendation: 'Strong Hire',
    panelUsed: ALL_INTERVIEWERS,
    technicalScore: 97,
    problemSolvingScore: 95,
    leadershipScore: 94,
    businessScore: 92,
    communicationScore: 96,
    standoutPraise:
      'Peerless clarity on multi-cloud networking, kernel bypass, and enterprise disaster recovery under partition scenarios.',
    keyStrengths: ['Multi-Cloud Mesh', 'eBPF Kernel Profiling', 'Disaster Recovery RPO=0'],
    quoteEvidence:
      '"Engineered cross-region multi-cloud active-active failover with sub-second DNS switchover and zero data loss under simulated cluster blackouts."',
    status: 'Evaluated',
  },
];
